name: Build VEX PLAYER Windows

on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4  # Tumesasisha kwenda v4

    - name: Set up Python
      uses: actions/setup-python@v5 # Tumesasisha kwenda v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "icon.ico" --name "VEX_PLAYER_FINAL" vex_main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # Hapa ndipo palikuwa na error, sasa ni v4
      with:
        name: VEX_PLAYER_WINDOWS_EXE
        path: dist/VEX_PLAYER_FINAL.exe
